// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naliruurguhzkuhwdwiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hbGlydXVyZ3Voemt1aHdkd2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTU0NTEsImV4cCI6MjA2Njg3MTQ1MX0.gDOuiFkMF8N_EFTXIaenanyAPCEPzJ_yPxCbQMtUaQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});